.TH SB_CHKOPTS "1" "June 2014" "sb_chkopts" "User Commands"
.SH NAME
sb_upload - Trivial script to check that the user's options file doesn't contain any old-style option names.
.SH "SEE ALSO"
The full documentation for
.B sb_chkopts
is maintained as a Texinfo manual.  If the
.B info
and
.B sb_chkopts
programs are properly installed at your site, the command
.IP
.B info sb_chkopts
.PP
should give you access to the complete manual.
