.TH SB_CLIENT "1" "June 2014" "sb_client" "User Commands"
.SH NAME
sb_client - A client for sb_xmlrpcserver.py.
.SH "DOCUMENTATION"
Just feed it your mail on stdin, and it spits out the same message
with the spambayes score in a new X-Spambayes-Disposition header.
.SH "SEE ALSO"
The full documentation for
.B sb_client
is maintained as a Texinfo manual.  If the
.B info
and
.B sb_client
programs are properly installed at your site, the command
.IP
.B info sb_client
.PP
should give you access to the complete manual.
