.TH SB_EVOSCORE "1" "June 2014" "sb_evoscore" "User Commands"
.SH NAME
sb_evoscore - A shim for integrating Spambayes and Ximian Evolution.
.SH "SEE ALSO"
The full documentation for
.B sb_evoscore
is maintained as a Texinfo manual.  If the
.B info
and
.B sb_evoscore
programs are properly installed at your site, the command
.IP
.B info sb_evoscore
.PP
should give you access to the complete manual.
